import { ErrorWrapper } from "./error-wrapper";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <h1>About</h1>
      <ErrorWrapper>{children}</ErrorWrapper>
    </div>
  );
}
