import { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial",
    template: "%s | Next.js Tutorial",
  },
  description: "Generated by Next.js",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header className="bg-blue-500 p-4 mb-4">
        <p>Header</p>
      </header>

      {children}

      <footer className="bg-gray-100 p-4 mt-4">
        <p>Footer</p>
      </footer>
    </>
  );
}
